export const CLERK_PUBLIC_KEY = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
export const CLERK_JWT_ISSUER_DOMAIN = process.env.NEXT_PUBLIC_CLERK_JWT_ISSUER_DOMAIN;
export const CONVEX_PUBLIC = process.env.NEXT_PUBLIC_CONVEX_URL;
