version: 1
reviews:
  enabled: true
  languages:
    - typescript
    - javascript
  checks:
    - performance
    - security
    - readability
    - maintainability
    - error-handling
  coverage:
    minimum: 60
    patch: 80
  fail_on:
    - high_security_issues
    - test_failures
  request_changes_workflow: true

auto_review: true

chat:
  auto_reply: true
