name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci
        env:
          CI: true

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: yarn build
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLERK_JWT_ISSUER_DOMAIN: ${{ secrets.NEXT_PUBLIC_CLERK_JWT_ISSUER_DOMAIN }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_WEBHOOK_SECRET: ${{ secrets.CLERK_WEBHOOK_SECRET }}
          CLERK_JWT_ISSUER_DOMAIN: ${{ secrets.CLERK_JWT_ISSUER_DOMAIN }}
          CLERK_APP_DOMAIN: ${{ secrets.CLERK_APP_DOMAIN }}
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/frckbrice/ai-powered-chat-app:sha-${{ github.sha }}
            ghcr.io/frckbrice/ai-powered-chat-app:main
          build-args: |
            NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            NEXT_PUBLIC_CLERK_JWT_ISSUER_DOMAIN=${{ secrets.NEXT_PUBLIC_CLERK_JWT_ISSUER_DOMAIN }}
            CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            CLERK_WEBHOOK_SECRET=${{ secrets.CLERK_WEBHOOK_SECRET }}
            CLERK_JWT_ISSUER_DOMAIN=${{ secrets.CLERK_JWT_ISSUER_DOMAIN }}
            CLERK_APP_DOMAIN=${{ secrets.CLERK_APP_DOMAIN }}
            CONVEX_DEPLOYMENT=${{ secrets.CONVEX_DEPLOYMENT }}
          sbom: true
          provenance: true
          cache-from: type=registry,ref=ghcr.io/frckbrice/ai-powered-chat-app:buildcache
          cache-to: type=registry,ref=ghcr.io/frckbrice/ai-powered-chat-app:buildcache,mode=max
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
